import type { Metadata } from "next"
import "./globals.css"
// LocaleSwitcher removed from global layout to avoid showing the selector on the login page.
import { NextIntlClientProvider } from "next-intl"
import fs from "fs"
import path from "path"

export const metadata: Metadata = {
  title: "Gestion Stations-Service",
  description: "Generated by create next app",
}

function getLocaleFromCookie(headers: Headers) {
  const cookie = headers.get("cookie") || ""
  const match = cookie.match(/(^|;)\s*NEXT_LOCALE=([^;]+)/)
  return match ? decodeURIComponent(match[2]) : "fr"
}

export default async function RootLayout({
  children,
  headers,
}: Readonly<{
  children: React.ReactNode
  headers?: Headers
}>) {
  const locale = getLocaleFromCookie(headers ?? new Headers())

  // Try messages folder first (project_root/messages), otherwise fallback to locales
  const tryPaths = [
    path.join(process.cwd(), "messages", `${locale}.json`),
    path.join(process.cwd(), "locales", `${locale}.json`),
  ]
  let messages: Record<string, any> = {}
  for (const p of tryPaths) {
    try {
      if (fs.existsSync(p)) {
        const raw = fs.readFileSync(p, "utf-8")
        messages = JSON.parse(raw)
        break
      }
    } catch (e) {
      console.warn(`Could not load locale messages from ${p}`, e)
    }
  }

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
